### PR TITLE
Luca's PCB DogTag Changes

### PR DESCRIPTION
**Pull request by LucaHanni**
PCB Dog Tag - Luca Hanni

### CODE REVIEW

**Comment by fcrema** [comment]
Nice work! You prob want to change your name's text box layer to top overlay (unless you want it written backwards on the back of the board)

**Review by fcrema — COMMENTED** [review]
Nice work! You prob want to change your name's text box layer to top overlay (unless you want it written backwards on the back of the board)

**Comment by liambontkes** [comment]
You might want to make it bigger, only about 3cm long right now.

**Review by liambontkes — APPROVED** [review]
Other than size, looks good.

**Pull request merged**
